site_name: Math 2024/25 Winter
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
markdown_extensions:
  - toc
  - tables
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - js/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
